version: '3.8'
services:
  postgres:
    image: postgres:13
    container_name: pg-database
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    networks:
      - my_network
    ports:
      - "5432:5432"

  prefect:
    image: prefecthq/prefect
    depends_on:
      - postgres
    networks:
      - my_network

networks:
  my_network:
